---
title: "SweCovICU Table 1"
author: "Sarah McIntyre"
date: "1/07/2020"
output:
  html_notebook: default
  html_document:
    df_print: paged
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(knitr)
library(kableExtra)
library(broom)

# Read in the data
swecovdata <- read_csv('SweCovICU_AnalysedData.csv',
                       col_types = cols(
                         .default = col_logical(),
                          Age = col_double(),
                          Gender = col_character(),
                          SAPS3TotalPoints = col_double(),
                          OxygenationIndexToUse = col_double(),
                          ICUDays = col_double(),
                          DischargedTo = col_character(),
                          CareResult = col_character(),
                          `DG021 days` = col_double(),
                          SOFATotalPoint = col_double(),
                          KDIGOMin = col_character(),
                          DaysToICUFromIllness = col_double(),
                          AgeGroup = col_character(),
                          nICUTransfersToUse = col_character(),
                          InvasiveMechVentDays = col_double(),
                          SAPS3TimeInHospitalNo0 = col_double(),
                          J809worst = col_character(),
                          DaysToDeath = col_double()
                         )) %>% 
  mutate(J809worst = J809worst %>% factor(levels = c('none', 'mild','moderate','severe')))


```

# Table 1

```{r}

table1data <- swecovdata %>% 
  select(Age, 
         `Age Group` = AgeGroup, 
         `> 65 years old` = Age65plus, 
         `Sex` = Gender,
         `SAPS III score` = SAPS3TotalPoints,
         `SOFA score on admission` = SOFATotalPoint,
         `Comorbidities` = ComorbidityAny, 
         `Hypertension` = RiskHypertension, 
         `Chronic heart diseases` = RiskChronicHeartDisease, 
         `Chronic lung disease` = RiskChronicLungDisease, 
         `Obesity` = RiskObesityToUse, 
         `Diabetes Mellitus` = RiskDiabetes, 
         `Chronic renal disease` = RiskChronKidneyDisease, 
         `Chronic hepatic disease` = RiskChronicLiverDisease, 
         `Chronic neuromuscular disease` = RiskNeuroMuscDisease, 
         `Immunosupression` = RiskReducedImmuneDefence, 
         `PaO2/FiO2 on admission` = OxygenationIndexToUse, 
         `Spent time in hospital prior to ICU admission` = TIHmore.than.0, 
         `Number of days spent in hospital prior to ICU admission` = SAPS3TimeInHospitalNo0, 
         `Symptom onset prior to ICU admission (days)` = DaysToICUFromIllness, 
         `Transfers to another ICU` = nICUTransfersToUse, 
         `ICU LOS (days)` = ICUDays, 
         `Discharge destination after ICU` = DischargedTo, 
         `Acute Respiratory Failure ` = J809worst, 
         `Acute Kidney Injury` = KDIGOMin, 
         `ICU mortality` = CareResult, 
         `30-day mortality` = Mortality30days)

stats_values <- function(x, digits = 1) {
  if (is.numeric(x)) {
      med = median(x, na.rm = TRUE) %>% round(., digits)
  Q1 = quantile(x, 1/4, na.rm = TRUE) %>% round(., digits)
  Q3 = quantile(x, 3/4, na.rm = TRUE) %>% round(., digits)
  output <- paste0(med, ' (',Q1,', ',Q3,')')
  } else {
    t <- tibble(v = x) %>%
      filter(!is.na(v)) %>% 
      group_by(v) %>% tally() %>% 
      mutate(pct = round(100*n/sum(!is.na(x)),digits))
    output <- paste0(t$n, ' (',t$pct,'%)') %>% paste0(collapse = '<br>')
  }
  
  if (is.logical(x)) { 
    t <- t %>% filter(v) 
    output <- paste0(t$n, ' (',t$pct,'%)') %>% paste0(collapse = '<br>')
  } else {
      output <- paste0('<br>',output)
    }
  
  output
}

value_labels <- function(x) {
  if (class(x) == 'numeric') {
    output <- 'Median (IQR):'
  } else {
    t <- tibble(v = x) %>%
      filter(!is.na(v)) %>% 
      group_by(v) %>% tally() 
    output <- paste0(t$v,':') %>% paste0(collapse = '<br>')
  }
  if (class(x) == 'logical') {
    t <- t %>% filter(v)
    output <- ''
  }
  output
}

table1data %>% 
  summarise_all(list(Label = ~value_labels(.),
                     Value = ~stats_values(.,1),
                    `Number with data` = ~sum(!is.na(.)))
               ) %>% 
  pivot_longer(everything(), 
               names_to = c('Variable','.value'),  
               names_sep = '_') %>% 
  mutate(Variable = paste0('<b>',Variable,'</b>', '<br>', Label)) %>% 
  select(-Label) %>% 
  kable(escape = F) %>% kable_styling(full_width = F, bootstrap_options = 'condensed')

```

# Table 2

```{r}

table2data <- swecovdata %>% 
  # put them in order
  select(Mortality30days, 
         `Invasive mechanical ventilation n (%)` = InvasiveMechanicalVentilation, 
         InvasiveMechVentDays, 
         `Noninvasive mechanical ventilation n (%)` = NonInvasiveMechVent, 
         `HFNO n (%)` = OxHighFlowNasalCanula, 
         `Prone positioning  n (%)` = CarePronePatient, 
         `ECMO n (%)` = ECMO, 
         `Specific pharmacotherapy n (%)` = SpecPharmAny, 
         `HC1/Cq n (%)` = CovidMedicineKlorokinfosfat, 
         `Lopinavir/ritonavir n (%)` = LopinavirOrRitonavir, 
         `Remdesivir n (%)` = CovidMedicineRemdesivir, 
         `Tocilizumab n (%)` = CovidMedicineTocilizumab, 
         `Steroids for ARDS n (%)` = CovidMedeicineSteroids, 
         `Other n (%)` = OtherPharmAny, 
         `Vasopressors/inotropes n (%)` = VasoInoAny, 
         `CRRT n (%)` = CRRT)

table2results <- table2data %>% 
  select(-InvasiveMechVentDays) %>% 
  pivot_longer(cols = -c('Mortality30days'), names_to = 'Treatment') %>% 
  mutate(Treatment = factor(Treatment, levels = names(table2data)[-c(1,3)])) %>% 
  group_by(Treatment) %>% 
  nest() %>% 
  mutate(fisher.result = map( data,
                              ~xtabs( ~ Mortality30days + value, data = .x) %>%
                                fisher.test(., conf.int = TRUE) %>%
                                tidy()  
                              ),
         `Number with data` = map_dbl(data, ~sum(!is.na(.$value)) ),
         AllN = map_dbl(data, ~sum(.$value, na.rm = TRUE) ),
         AllSurvivors = map_dbl(data, ~sum(.$Mortality30days == FALSE, na.rm = TRUE) ),
         AllNonSurvivors = map_dbl(data, ~sum(.$Mortality30days == TRUE, na.rm = TRUE) ),
         SurvivorsN = map_dbl(data, ~sum(.$value & .$Mortality30days == FALSE, na.rm = TRUE) ),
         `Non-survivorsN` = map_dbl(data, ~sum(.$value & .$Mortality30days == TRUE, na.rm = TRUE))
  ) %>% 
  unnest(fisher.result)

table2 <- table2results %>% 
  mutate(
    All = if_else(AllN > 20, 
                  paste0(AllN,' (', round(100*AllN/`Number with data`,1), '%)'),
                  '< 20'),
    Survivors = if_else(SurvivorsN > 10 & `Non-survivorsN` > 10, 
                  paste0(SurvivorsN,'/',
                         AllSurvivors, 
                         ' (', round(100*SurvivorsN/AllSurvivors,1), '%)'
                         ),
                  '-'),
    `Non-survivors` = if_else(SurvivorsN > 10 & `Non-survivorsN` > 10, 
                  paste0(`Non-survivorsN`,'/',
                         AllNonSurvivors, 
                         ' (', round(100*`Non-survivorsN`/AllNonSurvivors,1), '%)'
                         ),
                  '-'),
    `p-value` = if_else(SurvivorsN > 10 & `Non-survivorsN` > 10, 
                  if_else(p.value < 0.001, '< 0.001', as.character(round(p.value,3))),
                  '-')
    ) %>% 
  select(Treatment, `Number with data`, All, Survivors, `Non-survivors`, `p-value`) 

quant_values <- function(x, digits = 1) {  
  med = median(x, na.rm = TRUE) %>% round(., digits)
  Q1 = quantile(x, 1/4, na.rm = TRUE) %>% round(., digits)
  Q3 = quantile(x, 3/4, na.rm = TRUE) %>% round(., digits)
  paste0(med, ' (',Q1,', ',Q3,')')
}

modeldays <- glm(Mortality30days ~ InvasiveMechVentDays, 
                family=binomial(link="logit"),
                        data = table2data)
table2 %>% 
  filter(Treatment == 'Invasive mechanical ventilation n (%)') %>% 
  bind_rows(
    
    table2data %>%
      summarise(
        Treatment = 'No. days of invasive mechanical ventilation median (IQR)',
        `Number with data` = sum(!is.na(InvasiveMechVentDays)),
        All = quant_values(InvasiveMechVentDays),
        Survivors = if_else(Mortality30days, as.numeric(NA), InvasiveMechVentDays) %>%
          quant_values(),
        `Non-survivors` = if_else(Mortality30days, InvasiveMechVentDays, as.numeric(NA)) %>% 
          quant_values(),
                p = coef(summary(modeldays))[2,4],
                `p-value` = if_else(p < 0.001, '< 0.001',as.character(round(p,3)))
            ) %>% 
              select(-p)
            
    ) %>% 
  bind_rows(table2 %>%
              filter(Treatment != 'Invasive mechanical ventilation n (%)')) %>% 
  kable(escape = F) %>% kable_styling(full_width = F, bootstrap_options = 'condensed')

```


# Table 3

```{r}

table3data <- swecovdata %>% 
  select(Mortality30days, 
         `Age Group` = AgeGroup,
         Age,
         Sex = Gender,
         `SAPS III score` = SAPS3TotalPoints,
         `SOFA score` = SOFATotalPoint,
         Obesity = RiskObesityToUse,
         `Diabetes Mellitus` = RiskDiabetes,
         Hypertension = RiskHypertension,
         `Chronic heart diseases` = RiskChronicHeartDisease, 
         `Chronic lung disease` = RiskChronicLungDisease, 
         `Chronic renal disease` = RiskChronKidneyDisease, 
         `Immunosuppression` = RiskReducedImmuneDefence, 
         `Time from symptom onset to ICU` = DaysToICUFromIllness, 
         `PAO2/FIO2 on admission` = OxygenationIndexToUse, 
         `Acute respiratory failure` = J809worst, 
         `Invasive mechanical ventilation` = InvasiveMechanicalVentilation, 
         `Noninvasive mechanical ventilation` = NonInvasiveMechVent, 
         HFNO = OxHighFlowNasalCanula, 
         `Prone positioning` = CarePronePatient, 
         `Specific pharmacotherapy*` = SpecPharmAny, 
         `Vasopressors/Inotropes` = VasoInoAny,
         CRRT, 
         `Transfer to other ICU` = ICUtransferred) %>% 
  mutate(Age = Age/20,
         `SAPS III score` = `SAPS III score`/20,
         `SOFA score` = `SOFA score`/10,
         `Time from symptom onset to ICU` = `Time from symptom onset to ICU`/14,
         `PAO2/FIO2 on admission` = `PAO2/FIO2 on admission`/10)

table3steps <- tibble(
  Variable = names(table3data)[names(table3data)!="Mortality30days"],
  UnitStep = case_when(Variable == 'Age' ~ '20 years',
                       Variable == 'SAPS III score' ~ '20 points',
                       Variable == 'SOFA score' ~ '10 points',
                       Variable == 'Time from symptom onset to ICU' ~ '14 days',
                       Variable == 'PAO2/FIO2 on admission' ~ '10 mmHg',
                       TRUE ~ '')
                      )

multivardata <- table3data %>% 
  select(Mortality30days,
         `Age Group`,
         Sex,
         `SAPS III score`,
         Obesity,
         `Diabetes Mellitus`,
         Hypertension,
         `Chronic heart diseases`, 
         `Chronic lung disease`, 
         `Chronic renal disease`, 
         `Immunosuppression`, 
         `Time from symptom onset to ICU`, 
         `Acute respiratory failure`, 
         `Invasive mechanical ventilation`, 
         `Noninvasive mechanical ventilation`, 
         HFNO, 
         `Prone positioning`, 
         `Specific pharmacotherapy*`, 
         CRRT, 
         `Transfer to other ICU`) %>% 
  na.omit() 

Nmulti <- multivardata %>% nrow()

# multivardata %>% 
#   summarise_all(list( n.valid = ~sum(!is.na(.))))


table3_labels <- function(x) {
  if (is.numeric(x)) {
    output <- 'Continuous. OR per increase of '
  } else {
    t <- tibble(v = x) %>%
      filter(!is.na(v)) %>% 
      group_by(v) %>% tally() 
  }
  if (!is.logical(x) & !is.numeric(x)) {
    t <- t %>% mutate(v = v %>% as.character())
    t$v[1] <- paste0('(Reference: ',t$v[1],')')
    output <- paste0(t$v,collapse = '<br>')
  }
  if (is.logical(x)) {
    t <- t %>% filter(v)
    output <- ''
  }
  output
}

univar <- function(dv, iv, digits =1) {
  unimodel <- glm(dv ~ iv, family=binomial(link="logit"))
  result <- exp(cbind(coef(unimodel), confint(unimodel))) %>% 
    round(.,1) %>% 
    cbind(coef(summary(unimodel))[,4]) %>%  
    as_tibble(rownames = 'v') %>% .[-1,] %>%
    set_names(c('v','OR', 'Q1', 'Q3', 'p')) %>% 
    mutate(sig = case_when(p < 0.001 ~ '***',
                           p < 0.01 ~ '**',
                           p < 0.05 ~ '*',
                           TRUE ~ ''))
  output <- paste0(result$OR, ' (', result$Q1, ', ', result$Q3,')',result$sig) %>% 
    paste0(collapse = '<br>') 
  if (!is.logical(iv)) output <- paste0('<br>',output)
  if (!is.logical(iv) & !is.numeric(iv)) output <- paste0('<br>',output)
  
  output
}

multimodel <- glm(Mortality30days ~
                    `Age Group` +
                     Sex +
                     `SAPS III score` +
                     Obesity +
                     `Diabetes Mellitus` +
                     Hypertension +
                     `Chronic heart diseases` + 
                     `Chronic lung disease` + 
                     `Chronic renal disease` + 
                     `Immunosuppression` + 
                     `Time from symptom onset to ICU` + 
                     `Acute respiratory failure` + 
                     `Invasive mechanical ventilation` + 
                     `Noninvasive mechanical ventilation` + 
                     HFNO + 
                     `Prone positioning` + 
                     `Specific pharmacotherapy*` + 
                     CRRT + 
                     `Transfer to other ICU`,
              family=binomial(link="logit"),
              data = table3data)

# summary(multimodel); exp(cbind(coef(multimodel), confint(multimodel)))  %>% round(.,1)

multivarResults <- exp(cbind(coef(multimodel), confint(multimodel))) %>% 
    round(.,1) %>% 
    cbind(coef(summary(multimodel))[,4]) %>%  
    as_tibble(rownames = 'v') %>% 
  filter(v!= '(Intercept)') %>%
    set_names(c('v','OR', 'Q1', 'Q3', 'p')) %>% 
    mutate(sig = case_when(p < 0.001 ~ '***',
                           p < 0.01 ~ '**',
                           p < 0.05 ~ '*',
                           TRUE ~ ''))


multivar <- function(iv,ivclass) {
  result <- multivarResults %>% 
    filter(str_detect(v, iv) & iv!='Age')
  if (nrow(result) > 0) {
    output <- paste0(result$OR, ' (', result$Q1, ', ', result$Q3,')',result$sig) %>%
      paste0(collapse = '<br>') 
    } else {output <- '-'}
  if (ivclass != 'logical') output <- paste0('<br>',output)
  if (ivclass != 'logical' & ivclass != 'numeric') output <- paste0('<br>',output)
  
  output
}

table3data %>% 
  summarise_at(vars(-Mortality30days),
               list(Label = ~table3_labels(.),
                    `Univariable OR (95% CI)` = ~ univar(Mortality30days, .),
                    varclass = ~class(.)
                    )) %>% 
  pivot_longer(everything(), 
               names_to = c('Variable','.value'),  
               names_sep = '_') %>% 
  full_join(table3steps) %>% 
  group_by(Variable) %>% 
  mutate(`Multivariable OR (95% CI)` = multivar(Variable,varclass)) %>% 
  ungroup() %>% 
  rename(!!paste0('Multivariable OR (95% CI) <br> n = ', Nmulti) := `Multivariable OR (95% CI)`) %>% 
  mutate(Variable = paste0('<b>',Variable,'</b>', '<br>', Label,UnitStep)) %>% 
  select(-c(Label,UnitStep, varclass)) %>% 
  kable(escape = F) %>% kable_styling(full_width = F, bootstrap_options = 'condensed')

```


