---
title: "SweCovICU data management"
author: "Sarah McIntyre"
date: "December 2020"
output:
  html_document:
    df_print: paged
  html_notebook: default
---

# load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(summarytools)
library(janitor)
library(knitr)
library(kableExtra)

```

# read in the data
```{r}

datafile <- '../Raw data/SweCOVID_ICU_201207_nopwd.xlsx'
basicdata <- read_excel(datafile, na='NULL', sheet = 'Basic data') 

diagnosisdata <- read_excel(datafile, na='NULL', sheet = 'AllDiagnoses', range = 'A1:TY1609')

SOFAdata <- read_excel(datafile, na='NULL', sheet = 'SOFA', range = 'A1:BX1609')

measuresdata <- read_excel(datafile, na='NULL', sheet = 'Measures', range = 'A1:BC1609')

SIRIdata <- read_excel(datafile, na='NULL', sheet = 'SIRI', range = 'A1:AZ1609')


```

# create variables with any "1" in a list of other variables
```{r}

# "Any" of a list variables

comorbiddata <- SIRIdata %>% 
  select(c(PersonalID,
           RiskHypertension,
           RiskChronicHeartDisease,
           RiskChronicLungDisease,
           RiskDiabetes,
           RiskChronKidneyDisease,
           RiskChronicLiverDisease,
           RiskNeuroMuscDisease,
           RiskReducedImmuneDefence,
           RiskObesity)) %>% 
  full_join(basicdata %>% select(c(PersonalID, ArrivalBMI))) %>% 
  mutate(BMIover30 = as.numeric(ArrivalBMI > 30),
         RiskObesityToUse = coalesce(BMIover30, RiskObesity)) %>% 
  select(-c(ArrivalBMI,BMIover30)) %>% 
      pivot_longer(cols = -c(PersonalID),
                   names_to = c('Comorbidity')) %>% 
      group_by(PersonalID) %>%
      summarise(ComorbidityAny = ifelse(all(is.na(value)),
                                        NA, sum(value, na.rm = TRUE)
                                        ) %>% sign() %>% as.logical()
                )

specpharmdata <- SIRIdata %>% 
  select(c(PersonalID,
           CovidMedicineKlorokinfosfat,
           CovidMedicineLopinavir,
           CovidMedicineLopinavirRitonavir,
           CovidMedicineRemdesivir,
           CovidMedicineTocilizumab,
           CovidMedeicineSteroids)) %>% 
      pivot_longer(cols = -c(PersonalID),
                   names_to = c('SpecificPharmacotherapy')) %>% 
      group_by(PersonalID) %>%
    summarise(SpecPharmAny = ifelse(all(is.na(value)), 
                              NA, sum(value, na.rm = TRUE)
                              ) %>% sign() %>% as.logical()
    )
  
otherpharmdata <- SIRIdata %>% 
  select(c(PersonalID,
           CovidMedicineDarunavir,
           CovidMedicineVitamineC,
           CovidMedicineOther)) %>%
  pivot_longer(cols = -c(PersonalID),
               names_to = c('OtherPharmacotherapy')) %>%
  group_by(PersonalID) %>%
  summarise(OtherPharmAny = ifelse(all(is.na(value)),
                                NA, sum(value, na.rm = TRUE)
                                ) %>% sign() %>% as.logical()
    )

vasodata <- SOFAdata %>%
  select(c(PersonalID,
           Dopamin,
           Adrenalin,
           Noradrenalin,
           Dobutamin,
           Levosimendan,
           Vasopressin)) %>%
  pivot_longer(cols = -c(PersonalID),
               names_to = c('VasopressorsInotropes')) %>% 
  mutate(valueBinary = case_when(value == 'No' ~ 0,
                                 (is.na(value) | value=='Missing') ~ as.numeric(NA),
                                 value != 'No' ~ 1
                                 )) %>%
  group_by(PersonalID) %>% 
  summarise(VasoInoAny = ifelse(all(is.na(valueBinary)), 
                              NA, sum(valueBinary, na.rm = TRUE)
                              ) %>% sign() %>% as.logical()
            )

```

# make the analysis dataset
```{r}
# Sensitivity analysis of patients admitted 6march- 5 april
# If risk estimates of the sensitivity analysis differ compared to whole cohort then:
# Log rank test for 30d mortality for patients admitted 6 march-5april vs 6 April-6May
# I think that was it. 

# timediffsec <- basicdata$AdmissionTime - basicdata$AdmissionRegistration
# 
# basicdata %>% 
#   select(AdmissionTime, AdmissionRegistration) %>% 
#   .[which(timediffsec != 0),] %>% View()
# 
# lubridate::seconds_to_period(max(timediffsec))

# basicdata$AdmissionRegistration[1] >= "2020-03-06 00:00:00 UTC"

# variables created above
swecovdata <- comorbiddata %>% 
  full_join(specpharmdata) %>% 
  full_join(otherpharmdata) %>% 
  full_join(vasodata) %>% 
  # select variables from basic data sheet
  full_join (basicdata %>% select(c(PersonalID,
                                    Deceased,
                                    Age,
                                    Gender,
                                    SAPS3TotalPoints,
                                    ArrivalBMI,
                                    OxygenationIndexToUse,
                                    NumberOfICUTransfers,
                                    SAPS3TimeInHospital, 
                                    ICUDays,
                                    DischargedTo,
                                    CareResult,
                                    OffRegistryDate,
                                    AdmissionRegistration,
                                    `DaysFromDischargeToOff-registry/Diseased`))) %>% 
  # select variables from measuers data sheet
  full_join(measuresdata %>% select(c(PersonalID,
                                      `DG021 min`,
                                      `DG021 days`,
                                      `DG023 min`,
                                      `DG028 min`,
                                      `SR320 min`,
                                      `DV023 days`,
                                      `DR020 min`))) %>% 
  # select variables from SOFA sheet
  full_join(SOFAdata %>% select(c(PersonalID,
                                  SOFATotalPoint,
                                  KDIGOMin))) %>% 
  # select variables from SIRI sheet
  full_join(SIRIdata %>% select(c(PersonalID,
                                  # specific
                                  CovidMedicineKlorokinfosfat,
                                  CovidMedicineLopinavir,
                                  CovidMedicineLopinavirRitonavir,
                                  CovidMedicineRemdesivir,
                                  CovidMedicineTocilizumab,
                                  CovidMedeicineSteroids,
                                  # comorbidities
                                  RiskHypertension,
                                  RiskChronicHeartDisease,
                                  RiskChronicLungDisease,
                                  RiskObesity,
                                  RiskDiabetes,
                                  RiskChronKidneyDisease,
                                  RiskChronicLiverDisease,
                                  RiskNeuroMuscDisease,
                                  RiskReducedImmuneDefence,
                                  DaysToICUFromIllness))) %>%
  # select variables from diagnoses sheet
  full_join(diagnosisdata %>% select(c(PersonalID,
                                       J809A,
                                       J809B,
                                       J809C,
                                       J809X))) %>% 
  # created/calculated variables
  mutate(Age65plus = Age >= 65,
         AgeGroup = case_when(Age < 50 ~ '<50',
                              between(Age,50,59) ~ '50-59',
                              between(Age,60,69) ~ '60-69',
                              between(Age,70,79) ~ '70-79',
                              Age >= 80 ~ '80+',
                              TRUE ~ as.character(NA)),
         # BMI / obesity
         BMIover30 = as.numeric(ArrivalBMI > 30),
         BMI40plus = as.numeric(ArrivalBMI >= 40),
         RiskObesityOld30 = coalesce(BMIover30, RiskObesity),
         RiskObesityNew40 = coalesce(BMI40plus, RiskObesity),
         
         OxygenationIndexToUse = OxygenationIndexToUse*7.50062, # kPa -> mmHg
         nICUTransfersToUse = if_else(NumberOfICUTransfers >= 3,
                                      '3+', as.character(NumberOfICUTransfers)),
         # ventilation
         InvasiveMechanicalVentilation = `DG021 min` > 0,
         InvasiveMechVentDays = if_else(`DG021 days`==0,
                                        as.numeric(NA), `DG021 days`),
         NonInvasiveMechVent = `DG023 min` > 0,
         OxHighFlowNasalCanula = `DG028 min` > 0,
         CarePronePatient = `SR320 min` > 0,
         ECMO = `DV023 days` >0,
         CRRT = `DR020 min` > 0,
         
         # medication
         LopinavirOrRitonavir = pmax(CovidMedicineLopinavir,
                                    CovidMedicineLopinavirRitonavir,
                                    na.rm = TRUE) %>% as.logical(),
         CovidMedicineKlorokinfosfat = as.logical(CovidMedicineKlorokinfosfat),
         CovidMedicineRemdesivir = as.logical(CovidMedicineRemdesivir),
         CovidMedicineTocilizumab = as.logical(CovidMedicineTocilizumab),
         CovidMedeicineSteroids = as.logical(CovidMedeicineSteroids),
         
         ICUtransferred = NumberOfICUTransfers > 0,
         TIHmore.than.0 = SAPS3TimeInHospital > 0,
         SAPS3TimeInHospitalNo0 = if_else(SAPS3TimeInHospital > 0,
                                          SAPS3TimeInHospital, as.numeric(NA)),
         DaysToICUFromIllness = if_else(DaysToICUFromIllness < 0, 
                                        as.numeric(NA), 
                                        DaysToICUFromIllness),
         
         # comorbidities
         ComorbidityAny = as.logical(ComorbidityAny),
         RiskHypertension = as.logical(RiskHypertension),
         RiskChronicHeartDisease = as.logical(RiskChronicHeartDisease),
         RiskChronicLungDisease = as.logical(RiskChronicLungDisease),
         RiskObesityOld30 = as.logical(RiskObesityOld30),
         RiskObesityNew40 = as.logical(RiskObesityNew40),
         RiskDiabetes = as.logical(RiskDiabetes),
         RiskChronKidneyDisease = as.logical(RiskChronKidneyDisease),
         RiskChronicLiverDisease = as.logical(RiskChronicLiverDisease),
         RiskNeuroMuscDisease = as.logical(RiskNeuroMuscDisease),
         RiskReducedImmuneDefence = as.logical(RiskReducedImmuneDefence),
         
         KDIGOMin = as.character(KDIGOMin),
         J809worst = case_when(J809C == 1 ~ 'severe',
                               J809B == 1 ~ 'moderate',
                               J809A == 1 ~ 'mild',
                               (J809X+J809A+J809B+J809C) == 0 ~ 'none',
                               J809X == 1 ~ as.character(NA)
                               ),
         
         # 30 day mortality and days to death
         # problem triggered: argument "x" is missing, with no default
         # but don't worry it's fine
         `DaysFromDischargeToOff-registry/Diseased` = 
           `DaysFromDischargeToOff-registry/Diseased` %>% parse_number(),
         `DaysFromDischargeToOff-registry/Diseased` = 
           if_else(`DaysFromDischargeToOff-registry/Diseased` < 0,
                   as.numeric(NA), 
                   `DaysFromDischargeToOff-registry/Diseased`),
         Mortality30days = recode(Deceased, Yes = TRUE, No = FALSE),
         DaysToDeath = as.Date(OffRegistryDate) - as.Date(AdmissionRegistration) - (`DaysFromDischargeToOff-registry/Diseased`),
         
         #6 march-5april vs 6 April-6May
         AdmissionPeriod = case_when(
           as.Date(AdmissionRegistration) >= "2020-03-06" &
             as.Date(AdmissionRegistration) <= "2020-04-05" ~ '6Mar-5Apr',
           as.Date(AdmissionRegistration) >= "2020-04-06" &
             as.Date(AdmissionRegistration) <= "2020-05-06" ~ '6Apr-6May',
           TRUE ~ as.Date(AdmissionRegistration) %>% as.character())
         ) %>% 
  select(-c(PersonalID,
            Deceased,
            #ArrivalBMI,
            #BMIover30,
            #RiskObesity,
            NumberOfICUTransfers,
            SAPS3TimeInHospital,
            J809X,
            J809A,
            J809B,
            J809C,
            `DG021 min`,
            `DG023 min`,
            `DG028 min`,
            `SR320 min`,
            `DV023 days`,
            `DR020 min`,
            CovidMedicineLopinavir,
            CovidMedicineLopinavirRitonavir,
            OffRegistryDate,
            AdmissionRegistration,
            `DaysFromDischargeToOff-registry/Diseased`
         )) %>%
  filter(!is.na(Mortality30days))

write_csv(swecovdata,'SweCovICU_AnalysedData.csv')

# swecovdata %>%
#   filter(Mortality30days & is.na(DaysToDeath)) %>% 
#   pull(PersonalID)

# swecovdata %>% 
#   filter(`DaysFromDischargeToOff-registry/Diseased` < 0)
# 
# swecovdata %>% 
#   tabyl(BMIover30) %>% 
#   adorn_totals() %>% 
#   adorn_pct_formatting()
# 
swecovdata %>%
  group_by(is.na(ArrivalBMI), RiskObesity) %>%
  tally()

swecovdata %>%
  filter(ArrivalBMI >=40 & RiskObesity == 0) %>% 
  pull(ArrivalBMI)

swecovdata %>%
  filter(ArrivalBMI <40 & RiskObesity == 1) %>% 
  summarise(minBMI = min(ArrivalBMI),
            maxBMI = max(ArrivalBMI))

swecovdata %>% 
  group_by(BMI40plus, RiskObesity) %>% 
  tally()

obesityplot <- swecovdata %>% 
  mutate(ArrivalBMI = ArrivalBMI %>% parse_number(),
         RiskObesity = RiskObesity %>% as.logical()) %>% 
  ggplot(aes(x = ArrivalBMI, fill = RiskObesity)) +
  facet_wrap(~RiskObesity, scales = 'free', ncol = 1) +
  geom_histogram(binwidth = 5, colour = 'black') + 
  coord_cartesian(xlim = c(0,80)) +
  theme_bw()


```

# Summary table

```{r echo=FALSE}
dfSummary(swecovdata) %>% view()
```


